### ISSUE TITLE
Making a custom Input View

### ISSUE THREAD

**Issue by JStrawn** [steve228uk/MessengerKit#13]
When I try to subclass `MSGInputView`, I get an `Overriding non-open class var outside of its defining module` error.

I tried subclassing `MSGImessageInputView` instead, but even though my view has a text view and a send button connected to the custom `InputView`, I get a crash when setting the textfield delegate in `MSGInputView`. Any advice for making a custom InputView? Thanks

**Comment by cyrilzakka** [comment]
I too would like to know how to customize the input view (to add an image)
