### ISSUE TITLE
Could not set text to message input view 

### ISSUE THREAD

**Issue by mkhakpaki** [steve228uk/MessengerKit#14]
Hi,
first things first thank you for this great library and hours that you saved for me.
in my case i needed to add custom inputView for adding additional features like attach and stickers but now i have a problem.
in my app users can edit their messages but because of **internal** protection level of text property of  MSGPlaceholderTextView i can't set text so user can edit it.
any ideas for accomplishing this?

**Comment by cbess** [comment]
I'm having the same issue, given the activity within this `Issues` section, I'm going to fork the proj an make the change myself. I recommend you do the same, until they commit the access level change.

**Comment by cbess** [comment]
I'm actually wanting the feature so that I can _restore_ unsent messages, so I need it as well.

**Comment by cbess** [comment]
@mkhakpaki I see you've made the change already :) You should make a PR to have it added.

**Comment by mkhakpaki** [comment]
actually i wast waiting for contributors to answer that this have reason or can i sen PR.but apparently they are busy.Anyway i am making the PR now.
