### ISSUE TITLE
issue with iphone 5s when testing!!

### ISSUE THREAD

**Issue by dverdugo85** [steve228uk/MessengerKit#17]
I have issue in height initial the app in the chat

view.inputViewContainer.bottomAnchor.constraint(equalTo: keyboardLayoutGuide.topAnchor).isActive = true

![image](https://user-images.githubusercontent.com/5117517/49668920-5f626380-fa3e-11e8-89b3-f23f0e959716.png)

Regards!!!

**Comment by sjoness** [comment]
@dverdugo85 what device is this running on? Is your MSGMessengerViewController constrained correctly?
