### ISSUE TITLE
Custom Input view is jumping upwards automatically without typing

### ISSUE THREAD

**Issue by V1992** [steve228uk/MessengerKit#26]
If I start typing on custom inputview textfield and go back to any previous screen. After that when I reopened MSGMessengerViewController screen for infinite times automatically the input view will jump up always.
I want to prevent this and instead of that the custom input view should only jumps up when start typing something on it. I dont find any solution for this. Pls help.
 
![skype_picture](https://user-images.githubusercontent.com/12439866/52050387-6c9b5a80-2576-11e9-9236-7fce0cc0ffcf.jpeg)

**Comment by sjoness** [comment]
@V1992 Thanks for reporting this. I will look into it at some point this weekend

**Comment by y25zhao** [comment]
Looks like this issue is still not resolved?

**Comment by dan007b3** [comment]
Sorry, to bother you, but it is resolved, was a stupid mistake on my part(I
declared the delegate in the wrong place), but I did notice that I can't
access the textviewdidchange function.

Greetings

Ekhorugue Daniel
