### ISSUE TITLE
iOS 9 Support

### ISSUE THREAD

**Issue by alessioarsuffi** [steve228uk/MessengerKit#30]
Hello guys, this is such a wonderful library!
I was wondering, why is iOS 9 not supported? I've forked the project and easily lowered deployment target to 9.0, after adding some 
    
    @available(iOS 9.0, *)

checks, library runs pretty smooth in iOS 9.
I can make a pull request if someone wants this too.

Let me know, thanks :)

**Comment by sjoness** [comment]
@alessioarsuffi go ahead and submit that PR bro. I'll take a look at it this weekend 👍

**Comment by alessioarsuffi** [comment]
Sure!

**Comment by sjoness** [comment]
Wont support iOS 9
