### ISSUE TITLE
How to add attachment button to MSGInputView

### ISSUE THREAD

**Issue by anaselfauri** [steve228uk/MessengerKit#32]
How to add attachment button to MSGInputView?

**Comment by alessioarsuffi** [comment]
You should Create a custom MSGInputView subclass. Create also a custom Xib. Add button to that xib and then link everything you need (IBAction & customization).

This is a very basic example:

    import MessengerKit

    class CustomInputView: MSGInputView {
	
	@IBOutlet weak var containerView: UIView!
        @IBOutlet weak var attachmentButton: UIButton!
	
	override open class var nib: UINib? {
		return UINib(nibName: "CustomInputView",
					 bundle: .main)
	}
	
	open override var tintColor: UIColor! {
		didSet {
			textView.tintColor = tintColor
			sendButton.tintColor = tintColor
		}
	}
	
	open override func awakeFromNib() {
		super.awakeFromNib()
		
		containerView.layer.borderColor = UIColor.lightGray.cgColor
		containerView.layer.borderWidth = 0.5
		containerView.layer.cornerRadius = 5
		
		textView.textContainerInset = UIEdgeInsets(top: 8, left: 10, bottom: 8, right: 0)
	}

        @IBAction func attachmentButtonPress (_ sender: UIButton) {
        }
    }

Once you're done with this, just replace in your Custom theme this property:

    var inputView: MSGInputView.Type { get }
   
example:

    var inputView: MSGInputView.Type = CustomInputView.self

**Comment by ios-applyjob** [comment]
how can i pass the button press to the MSGMessengerViewController?
