### ISSUE TITLE
NSInternalInconsitencyException

### ISSUE THREAD

**Issue by george-gymamigo** [steve228uk/MessengerKit#34]
When the user presses the send button upon trying to insert new message the following error is thrown:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (0), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).'

**Comment by sjoness** [comment]
@george-gymamigo This looks like an issue with your [NSFetchedResultsControllerDelegate](https://developer.apple.com/documentation/coredata/nsfetchedresultscontrollerdelegate) implementation.

Could you provide any furthers on your implementation of the delegate methods, and/or how you're fetching the data.

**Comment by george-gymamigo** [comment]
Hi Sam

I sorted the issue thanks, however for some reason if the message is longer than one line, the message bubble doesn’t get bigger? How can I fix this?

On 23 May 2019, at 4:09 pm, Sam Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


@george-gymamigo<https://github.com/george-gymamigo> This looks like an issue with your NSFetchedResultsControllerDelegate<https://developer.apple.com/documentation/coredata/nsfetchedresultscontrollerdelegate> implementation.

Could you provide any furthers on your implementation of the delegate methods, and/or how you're fetching the data.

**Comment by sjoness** [comment]
Closing as the initial issue has been resolved as user error. The new issues has been reported in #49
