### ISSUE TITLE
MSGMessengerViewController unregisters host app observers from NotificationCenter

### ISSUE THREAD

**Issue by parrotbait** [steve228uk/MessengerKit#36]
Version: 1.0.4
Reproduction rate: always
Description:
Currently a VC that derives from MSGMessengerViewController.swift is hidden the default behaviour is to remove the VC from the NotificationCenter. However this affects ALL observers in the derived VC, not just those registered by MessengerKit. 

Case in point, my app needs to keep a notification with NotificationCenter that happens as soon as the app comes to the foreground (via deep link). Because MSGMessengerViewController unregisters on going to the background this behaviour is broken. Now I need to re-register with NotificationCenter after calling super in viewDidDisappear to keep the correct behaviour in place.

MSGMessengerViewController should only unregister from notifications that it has registered for before instead of unregistering all:
`NotificationCenter.default.removeObserver(self, name: UIKeyboardWillShow, object: nil)`

**Comment by sjoness** [comment]
Hey @parrotbait, sorry I took so long to get around to this!

I have pushed a change in commit c36fdcf93a1288215e1e7b8e0fa533477a041e34. Can you check if this resolves the issue you were having?

**Comment by parrotbait** [comment]
Yep - thanks that resolves it.

**Comment by sjoness** [comment]
Awesome!
