### ISSUE TITLE
How to add custom header/footer and why can't I change the font size of the bubble text?

### ISSUE THREAD

**Issue by dan007b3** [steve228uk/MessengerKit#38]

**Comment by smhk** [comment]
### To change font size ...

It's just the ".font" property in the style. So for example:

```
override var style: MSGMessengerStyle {
	var s = MessengerKit.Styles.iMessage
	s.incomingBubbleColor = .white
	s.outgoingBubbleColor = .white
	
	s.incomingTextColor = .black
	s.outgoingTextColor = .black
	
	s.font = .systemFont(ofSize: 14)
	return s
}
```

The relevant file is "MSGIMessageStyle.swift"

Note that in the file, the default is

`public var font: UIFont = .preferredFont(forTextStyle: .body)
`

which explains why generally it is pretty large by default.
