### ISSUE TITLE
MSGImessageInputView.nib

### ISSUE THREAD

**Issue by marcospolanco** [steve228uk/MessengerKit#4]
It would be super helpful to make this an open class var, to make it easier to extend outside the module.
`
    
    override open class var nib: UINib? {
        return UINib(nibName: "MSGImessageInputView",
                     bundle: MessengerKit.bundle)
    }

    `

**Comment by steve228uk** [comment]
This seems like a great idea and was definitely my intention when writing it. Please feel free to submit a pull request if you have time. If not I'll take a look at this when I'm back at work Monday.

**Comment by marcospolanco** [comment]
https://github.com/steve228uk/MessengerKit/pull/6
