### ISSUE TITLE
Height of bubble not growing when text is a variable 

### ISSUE THREAD

**Issue by cnovelini** [steve228uk/MessengerKit#40]
Hey,
All works perfectly when trying the examples... but whenever I pull text from the Database and pass it to MSGMessage the bubble remains a one line height.

Any clues on what is going on?

Thanks

**Comment by shauntif** [comment]
I have the same issue

**Comment by cnovelini** [comment]
I seem to have fixed the issue.
Make sure the ID of the MSGMessage its not the same among the messages you create.

Cheers,
