### ISSUE TITLE
Hide/add new view to hierarchy

### ISSUE THREAD

**Issue by kharitonovAL** [steve228uk/MessengerKit#41]
Hi!
First, I wonder, is there a way to hide `messageInputView` param, because for certain cases I don't need it.
And second - how to add another subviews in hierarchy? or just button?
Are there any legal way to di this things?
Thanks!

**Comment by sjoness** [comment]
Hi @kharitonovAL, I will be working on implementing a simple way to hide the input view this weekend (fingers crossed).

With regard to adding subviews, where do you want to do this? In the InputView? The UICollectionView?

**Comment by sjoness** [comment]
Closing due to lack of requirements
