### ISSUE TITLE
While installing the pod 'MessengerKit' without git command

### ISSUE THREAD

**Issue by KOSURUUDAYSAIKUMAR** [steve228uk/MessengerKit#45]
While installing the pod 'MessengerKit' without git command
It is not installing properly and installed old version. In that there is no files inside the pod folder.

**Comment by sjoness** [comment]
@KOSURUUDAYSAIKUMAR the entry in your Podfile should look like the following:

```
pod 'MessengerKit', :git => 'https://github.com/steve228uk/MessengerKit.git'
```
