### ISSUE TITLE
Inserting Image Causes Constraint Issues

### ISSUE THREAD

**Issue by BrandonBisbano** [steve228uk/MessengerKit#46]

**Comment by BrandonBisbano** [comment]
Inserting text and then an image sometimes creates a situation as seen in the sample image below. In addition, sometimes when inserting an image and then text the text bubble retains the height of an image.
![FB9232CA-9ADC-42AE-8D2B-0EFC5A621D08](https://user-images.githubusercontent.com/46690038/62630311-b0439800-b8fc-11e9-9698-6f08e36e8c7b.png)

**Comment by ruanorz** [comment]
Ensure that you are using an unique ID for each message.

**Comment by sjoness** [comment]
Closing this as @ruanorz is correct. Ensure that each MSGMessage instance has a unique ID
