### ISSUE TITLE
image from url

### ISSUE THREAD

**Issue by fuatkarip** [steve228uk/MessengerKit#47]
hi
how can i add image from url
i try .image but cant load

thx

**Comment by ios-applyjob** [comment]
I am having the same issue while loading image or video asynchronously..Please look into this

**Comment by ios-applyjob** [comment]
Found a working solution:
Create a custom image incoming and image outgoing cell.
change arguments in MSGMessageBody.image to (UIImage, String).
Set the image in the custom cell from the URL. I personally used Kingfisher.

**Comment by ruanorz** [comment]
> Found a working solution:
> Create a custom image incoming and image outgoing cell.
> change arguments in MSGMessageBody.image to (UIImage, String).
> Set the image in the custom cell from the URL. I personally used Kingfisher.

Please, can you share your solution? Thank you 🙏

**Comment by sjoness** [comment]
Hi @fuatkarip, @ruanorz

[PR#48](https://github.com/steve228uk/MessengerKit/pull/48) was just merged and offers this feature. Check it out 😁
