### ISSUE TITLE
multiline messages ui is not proper

### ISSUE THREAD

**Issue by ritz122** [steve228uk/MessengerKit#49]
When adding new multiline message in section it looks like below screen shot

![Simulator Screen Shot - iPhone 5s - 2019-09-02 at 11 49 05](https://user-images.githubusercontent.com/49153256/64105440-e1947400-cd93-11e9-8882-956a419de211.png)

**Comment by korantengNanaYaw** [comment]
Any fix on this bug ?

**Comment by sjoness** [comment]
@ritz122 @korantengNanaYaw This seems like #46.

Can you confirm that you guys have unique identifiers for each `MSGMessage` instance?
