### ISSUE TITLE
Pull to refresh messages

### ISSUE THREAD

**Issue by RajChanchal** [steve228uk/MessengerKit#50]
Hello, how can we add pull to refresh to load more messages.

Like I use following component: https://github.com/CRAnimation/CRRefresh
On  collectionView/tableview. But MesengerKit collectionview is put private so cannot add CRRefresh. Any suggestions?

**Comment by Andrew-Chen-Wang** [comment]
Use WebSockets instead of pull to refresh. Better for UX.

**Comment by sjoness** [comment]
I'm going to close this as a duplicate of #61 because it seems you want the same functionality
