### ISSUE TITLE
How to add a small simple UIlabel at the bottom to the chat cell 

### ISSUE THREAD

**Issue by korantengNanaYaw** [steve228uk/MessengerKit#56]
i need help adding a small UILabel to the text chat bubble  which will display the time the message was sent/created, after i edited the xib file , and added the UIlabel it breaks the existing constraint . any help will be appreciated

![IMG_82CE77B69016-1](https://user-images.githubusercontent.com/20087958/70657140-337e4d00-1c53-11ea-9ef3-8af006089a69.jpeg)

**Comment by sjoness** [comment]
@korantengNanaYaw you need to subclass `MSGSectionReusableView` and create a footer view for your style. See [MSGImessageFooterView.swift](https://github.com/steve228uk/MessengerKit/blob/master/MessengerKit/Collection%20View/Header%20Footers/iMessage/MSGImessageFooterView.swift) for example. You then need to register the footer view in your `MSGCollectionView` subclass e.g. [MSGImessageCollectionView.swift](https://github.com/steve228uk/MessengerKit/blob/master/MessengerKit/Collection%20View/Styles/iMessage/MSGImessageCollectionView.swift).
