### ISSUE TITLE
Send on enter

### ISSUE THREAD

**Issue by TimBroddin** [steve228uk/MessengerKit#58]
Hi,

Could you point me in the right direction for making the input field single line, and allowing send on enter?

**Comment by sjoness** [comment]
Hey @TimBroddin,

There are a few options that you could try here https://stackoverflow.com/a/704197/572027. Using a `UITextField` in place of the `UITextView` is probably the best option. However single line text entry is not a use-case we want to support right now in this library, so you would have to use your own fork if you want to make this change.
