### ISSUE TITLE
Quick question, just add an inputAccessoryView ??

### ISSUE THREAD

**Issue by smhk** [steve228uk/MessengerKit#71]
I want to simply add an inputAccessoryView to the keyboard,

`messageInputView.textView.inputAccessoryView =`

does not work, "Cannot assign to property: 'inputAccessoryView' is a get-only property"

what's the easy way to add . inputAccessoryView ??

![Screen Shot 2020-06-26 at 9 44 39 AM](https://user-images.githubusercontent.com/3938526/85869718-af745880-b791-11ea-9ef7-1121fd1f26ff.png)

**Comment by sjoness** [comment]
@smhk currently the textView occupies the space where an inputAccessoryView would go. Is this something that you would like in-place of the textView, or above it?

**Comment by smhk** [comment]
ah makes sense, thanks for the reply and explanation, @sjoness 

due to customization needs. in the end it was easier for us to just use a table view rather than a library

very best, cheers
