### ISSUE TITLE
Could not load the "Arrow" image

### ISSUE THREAD

**Issue by gersonjanhuel** [steve228uk/MessengerKit#8]
Hi there, awesome framework! Quick question :

After run pod install, implement MSGMessengerViewController, then somehow I got this error :  

`Could not load the "Arrow" image referenced from a nib in the bundle with identifier "org.cocoapods.MessengerKit"`

What did I missed ?  

MessengerKit v 1.0.0 

<img width="1238" alt="screen shot 2018-07-03 at 12 31 01 pm" src="https://user-images.githubusercontent.com/2060000/42200336-fdb3f9ac-7ebc-11e8-8a75-44e2ec25b335.png">

It did work if I change the MSGMessengerStyle to .travamigos style. 

But the arrow is still missing... 

![screen shot 2018-07-03 at 12 58 38 pm](https://user-images.githubusercontent.com/2060000/42201221-0be9a8ec-7ec1-11e8-9fe6-775526591cfb.png)

**Comment by gersonjanhuel** [comment]
I got it fixed by set the image "Arrow" Target Membership to "MessengerKit". 

Somehow it is "unchecked" by default. 

<img width="899" alt="screen shot 2018-07-04 at 8 13 45 am" src="https://user-images.githubusercontent.com/2060000/42251545-38da6868-7f62-11e8-92cb-2a65362ed1b5.png">

**Comment by steve228uk** [comment]
Strange that it wasn't already… It should have been in the MessengerKit-MessengerKit Bundle which the `MessengerKit.bundle` property would return

**Comment by steve228uk** [comment]
Could you also try running `pod update`?

**Comment by gersonjanhuel** [comment]
did tried... but no luck... the issue still happen.

**Comment by steve228uk** [comment]
Thanks for letting me know, I'll do some investigation.

**Comment by fbarraganef** [comment]
same problem, I was able to fix setting the image "Arrow" Target Membership to "MessengerKit" too.

**Comment by Ryskalo** [comment]
same.. can't load bubble images too with iMessage style

**Comment by sukhrabbek** [comment]
same problem, I could not fix even by setting the image "Arrow" Target Membership to "MessengerKit" too.

**Comment by sjoness** [comment]
Closed by #21
