### ISSUE TITLE
Example project link returning 404

### ISSUE THREAD

**Issue by acerts04** [steve228uk/MessengerKit#9]
Hey there! 

I wanted to take a look and follow the example project, but when clicking on the link it gives a 404 error. Wanted to report it. Thanks!

**Comment by steve228uk** [comment]
Hey @acerts04! Are you able to let me know where you're seeing this link?

**Comment by steve228uk** [comment]
@acerts04 Thank you, that links been fixed. The example can be found here: https://github.com/steve228uk/MessengerKit/tree/master/Example/
